# Cops docs: https://docs.rubocop.org/rubocop/cops.html
# Default config: https://github.com/rubocop/rubocop/blob/master/config/default.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 200
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/CollectionMethods:
  Enabled: true
Style/Copyright:
  Enabled: false # we have copyright in the readme
Style/Documentation:
  Enabled: false # we have documentation in the readme
Style/Encoding:
  Enabled: false # we have some sources with non-ascii chars (in utf-8 encoding), we like stating encoding explicitly
Style/IfUnlessModifier:
  Enabled: false # we like to use if/unless blocks for single-line expressions or statements that are long, avoiding making the line even longer with trailing if/unless modifier
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PercentLiteralDelimiters:
  Enabled: false # it's better to use `%w{}` syntax, because the braces are the same as in `%r{}`
