# Jekyll
source: .
destination: _site
exclude:
  - GPATH
  - GRTAGS
  - GTAGS
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - package-lock.json
  - package.json
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll/minibundle
timezone: Europe/Helsinki
baseurl: /tkareine.org
port: 8080
url: https://tkareine.github.io

# Custom
author: Tuomas Kareinen
feed_subscription: "https://feeds.feedburner.com/tkareine"
feed_title: "Tuomas Kareinen's blog"
title: "Tuomas Kareinen's blog"
