# Jekyll
source: .
destination: _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - package-lock.json
  - package.json
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll/minibundle
timezone: Europe/Helsinki
baseurl: /
url: "http://tkareine.org"
port: 8080

# Custom
author: Tuomas Kareinen
disqus_shortname: tkareine
feed_subscription: "https://feeds.feedburner.com/tkareine"
feed_title: "Tuomas Kareinen's blog"
google_analytics:
  tracking_id: UA-17308352-1
  config: "'auto'"
title: "Tuomas Kareinen's blog"
