# Jekyll
source: .
destination: _site
exclude:
  - GPATH
  - GRTAGS
  - GTAGS
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - package-lock.json
  - package.json
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /articles/:title.html
plugins:
  - jekyll/minibundle
timezone: Europe/Helsinki
baseurl: ""
port: 8080
url: https://tkareine.org

# Custom
author: Tuomas Kareinen
feed_subscription: "https://feeds.feedburner.com/tkareine"
feed_title: "Tuomas Kareinen's blog"
title: "Tuomas Kareinen's blog"
